"""Таблицы README подставляются скриптом между маркерами."""

from __future__ import annotations

import pytest
from test_dataset import UNANSWERABLE, q

from kz_labor_rag.eval.dataset import EvalDataset, EvalQuestion
from kz_labor_rag.eval.report import (
    MissingBlockError,
    dataset_summary,
    replace_block,
    strip_generated_comment,
)

README = "intro\n<!-- BEGIN t -->\nold\n<!-- END t -->\noutro\n"


def test_block_is_replaced_and_the_rest_kept():
    out = replace_block(README, "t", "| new |")
    assert out == "intro\n<!-- BEGIN t -->\n| new |\n<!-- END t -->\noutro\n"


def test_replacement_is_idempotent():
    once = replace_block(README, "t", "x")
    assert replace_block(once, "t", "x") == once


def test_missing_markers_are_an_error():
    with pytest.raises(MissingBlockError):
        replace_block("no markers", "t", "x")


def test_generated_comment_is_dropped():
    assert strip_generated_comment("<!-- generated by x -->\n| a |\n") == "| a |"


def test_dataset_summary_counts_verified_separately():
    ds = EvalDataset(
        questions=(
            q(id="a"),
            q(id="b", verified=False, origin="real"),
            EvalQuestion.from_dict(UNANSWERABLE),
        )
    )
    text = dataset_summary(ds)
    assert "3 questions" in text
    assert "2 answerable, 1 unanswerable" in text
    assert "**1 verified by hand**" in text
    assert "| condition | 2 | 1 |" in text


def test_empty_block_is_filled():
    # Свежий README: маркеры стоят вплотную, содержимого ещё нет.
    out = replace_block("<!-- BEGIN t -->\n<!-- END t -->\n", "t", "| a |")
    assert out == "<!-- BEGIN t -->\n| a |\n<!-- END t -->\n"
